Repository Arquisoft/dede_es6c, pull requests merged in 2022-03, with the labels that each got.

#66 Actualización modelo de dominio
  docs/08_concepts.adoc
  docs/images/08_domain_model.png
Labels: documentation

#67 Documentacion 09
  docs/09_design_decisions.adoc
Labels: documentation

#69 Pequeño cambio
  docs/02_architecture_constraints.adoc
Labels: documentation

#75 Lista productos y cards productos
  webapp/package-lock.json
  webapp/package.json
  webapp/public/index.html
  webapp/src/ProductList.tsx
  webapp/src/components/ProductCard.tsx
  webapp/src/components/Products.tsx
  webapp/src/images/coche.jpg
  webapp/src/index.tsx
  webapp/src/testProducts.js
Labels: user interface

#82 NavBar
  webapp/src/App.css
  webapp/src/components/NavBar.tsx
  webapp/src/images/logo.jpg
  webapp/src/images/logo_opt.jpg
  webapp/src/index.tsx
Labels: enhancement, user interface

#88 Vista home básica
  webapp/src/App.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/NavBar.tsx
Labels: user interface

#90 Footer
  webapp/src/App.css
  webapp/src/App.tsx
  webapp/src/ProductList.tsx
  webapp/src/components/Footer.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/estilos/estilo.css
  webapp/src/images/coche_home.png
  webapp/src/images/logo.jpg
  webapp/src/images/logo.png
  webapp/src/images/logo_opt.jpg
  webapp/src/index.css
  webapp/src/index.tsx
Labels: user interface

#105 Actualizacion Documentacion-Diagrama ver ususarios
  docs/images/Diagrama_secuencia_ver_usuarios.png
Labels: documentation

#111 Obtencion direccion POD
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/LogOutButton.tsx
  webapp/src/SolidConection.tsx
  webapp/src/SolidDisconection.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/getAddress.ts
  webapp/src/profile.tsx
Labels: enhancement

#115 Geocoder
  restapi/api.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/server.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/SolidConection.tsx
  webapp/src/SolidDisconection.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Products.tsx
  webapp/src/components/ResumenCompra.tsx
  webapp/src/index.tsx
  webapp/src/profile.tsx
  webapp/src/testProducts.js
Labels: backend

#113 Actualización documentación apartado 9
  docs/09_design_decisions.adoc
Labels: documentation
