Repository Arquisoft/dede_es6c, pull requests merged in 2022-05, with the labels that each got.

#198 Cambios para arreglo coverage
  webapp/jest.config.ts
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/LogOutButton.tsx
  webapp/src/SolidDisconection.tsx
  webapp/src/components/profile.tsx
  webapp/src/tests/SolidConection.test.tsx
Labels: test

#200 Arreglos para e2e
  webapp/e2e/steps/authenticated-purchase-steps.ts
  webapp/e2e/steps/user-authentication.steps.ts
  webapp/src/App.tsx
  webapp/src/SolidDisconection.tsx
Labels: test

#201 Arreglos tests e2e
  webapp/e2e/steps/authenticated-purchase-steps.ts
  webapp/e2e/steps/user-authentication.steps.ts
  webapp/src/App.tsx
  webapp/src/SolidDisconection.tsx
Labels: test

#202 Pruebas arreglos test e2e
  webapp/e2e/steps/authenticated-purchase-steps.ts
  webapp/e2e/steps/user-authentication.steps.ts
Labels: test

#203 Pruebas para test e2e
  webapp/e2e/steps/authenticated-purchase-steps.ts
  webapp/e2e/steps/user-authentication.steps.ts
Labels: test

#204 Pruebas para test e2e
  webapp/e2e/steps/authenticated-purchase-steps.ts
  webapp/e2e/steps/user-authentication.steps.ts
Labels: test

#205 Documentacion 05
  docs/05_building_block_view.adoc
  docs/images/Level1.png
  docs/images/Level2.png
  docs/images/Level3.png
Labels: documentation

#206 Documentación 5
  docs/05_building_block_view.adoc
  docs/images/Level1.png
  docs/images/Level2.png
  docs/images/Level3.png
Labels: documentation

#222 Cambios ficheros de webapp
  docs/01_introduction_and_goals.adoc
  webapp/src/App.tsx
  webapp/src/Products.tsx
  webapp/src/profile.tsx
Labels: test

#224 Apartado Documentación Testing
  docs/12_testing.adoc
  docs/13_glossary.adoc
Labels: documentation

#226 Documentación de Testing
  docs/12_testing.adoc
  docs/images/E2ETest.png
  docs/images/GatlingTest_1.1.png
  docs/images/GatlingTest_1.2.png
  docs/images/GatlingTest_2.1.png
  docs/images/GatlingTest_2.2.png
  docs/images/RestapiTest.png
  docs/images/WebappTest.png
Labels: documentation

#227 Documentación punto 5, actualización
  docs/05_building_block_view.adoc
Labels: documentation

#230 Quitar broker inrupt
  webapp/src/SolidConection.tsx
Labels: backend

#231 Quitar Broker inrupt
  docs/05_building_block_view.adoc
  webapp/src/SolidConection.tsx
Labels: backend
