Repository Arquisoft/dede_es6c, pull requests merged in 2022-04, with the labels that each got.

#117 Historial
  restapi/api.ts
  restapi/models/History.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/SolidConection.tsx
  webapp/src/SolidDisconection.tsx
  webapp/src/api/api.ts
  webapp/src/components/Cart.tsx
  webapp/src/components/History.tsx
  webapp/src/components/Home.tsx
  webapp/src/getAddress.ts
  webapp/src/profile.tsx
  webapp/src/profileInfo.ts
  webapp/src/shared/shareddtypes.ts
Labels: user interface, backend

#119 Prueba para despliegue en aws
  docs/09_design_decisions.adoc
  docs/images/Diagrama_secuencia_ver_usuarios.png
  package-lock.json
  package.json
  restapi/api.ts
  restapi/models/History.ts
  restapi/models/Product.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/schemas/productSchema.ts
  restapi/server.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.styles.ts
  webapp/src/App.tsx
  webapp/src/LogOutButton.tsx
  webapp/src/ProductList.tsx
  webapp/src/SolidConection.tsx
  webapp/src/SolidDisconection.tsx
  webapp/src/api/api.ts
  webapp/src/components/Cart.styles.ts
  webapp/src/components/Cart.tsx
  webapp/src/components/Cartitem.styles.ts
  webapp/src/components/Cartitem.tsx
  webapp/src/components/EmailForm.test.tsx
  webapp/src/components/EmailForm.tsx
  webapp/src/components/History.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/ProductCard.tsx
  webapp/src/components/Products.tsx
  webapp/src/components/ResumenCompra.tsx
  webapp/src/components/ShoppingCart.tsx
  webapp/src/components/UserList.test.tsx
  webapp/src/components/UserList.tsx
  webapp/src/estilos/estilo.css
  webapp/src/index.tsx
  webapp/src/profile.tsx
  webapp/src/profileInfo.ts
  webapp/src/shared/shareddtypes.ts
  webapp/src/testProducts.js
Labels: question

#122 Cambio super pequeño
  webapp/src/profile.tsx
Labels: bug

#123 Cambio super pequeño
  webapp/src/App.test.tsx
Labels: bug

#124 Prueba de despliegue sin tests
  .github/workflows/asw2122.yml
  restapi/tests/api.test.ts
Labels: bug

#125 Prueba de despliegue sin tests
  .github/workflows/asw2122.yml
Labels: bug

#126 Prueba de despliegue sin tests
  .github/workflows/asw2122.yml
Labels: bug

#140 Actualización modelo de dominio
  docs/08_concepts.adoc
  docs/images/08_domain_model.png
Labels: documentation

#146 Para prueba despliegue con tests
  .github/workflows/asw2122.yml
Labels: deployment

#154 Precio de envío en carrito y en resumen compra
  webapp/public/images/Lamborghini_Sprint.png
  webapp/public/images/Montesa_Repsol4RT.png
  webapp/public/images/Smart_Fortwo.png
  webapp/public/images/Subaru_ImprezaWRC.png
  webapp/public/images/Suplemento_Dados.png
  webapp/src/components/Cart.tsx
  webapp/src/components/ResumenCompra.tsx
  webapp/src/components/ShoppingList.tsx
Labels: enhancement

#168 Recovery enhancements
  docker-compose.yml
  docs/09_design_decisions.adoc
  restapi/package-lock.json
  webapp/package-lock.json
  webapp/src/api/api.ts
Labels: documentation, deployment, security

#170 Order
  restapi/api.ts
  restapi/models/History.ts
  restapi/package-lock.json
  restapi/package.json
  webapp/src/api/api.ts
  webapp/src/components/History.tsx
  webapp/src/components/ShoppingList.tsx
  webapp/src/shared/shareddtypes.ts
Labels: backend

#171 Aplicación medidas relativas
  webapp/src/LogOutButton.tsx
  webapp/src/components/Cart.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/ShoppingList.tsx
  webapp/src/profile.tsx
Labels: deployment

#175 Solución crypto restapi
  restapi/api.ts
  webapp/src/components/Cart.tsx
Labels: backend

#177 Develop
  restapi/api.ts
  restapi/controller/authenticationController.ts
  restapi/server.ts
  webapp/src/components/Cart.tsx
  webapp/src/components/ShoppingList.tsx
Labels: priority

#186 Testse2e
  webapp/e2e/features/unauthenticated-purchase.feature
  webapp/e2e/steps/register-form.steps.ts
  webapp/e2e/steps/unauthenticated-purchase.steps.ts
  webapp/jest.config.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/NavBar.tsx
Labels: test
